[package]
org = "sameeragunarathne"
name = "v2_to_fhir_service"
version = "0.1.0"
distribution = "2201.3.1"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "wso2healthcare"
name = "healthcare.fhir.r4"
version = "0.1.13"

[[dependency]]
org = "wso2healthcare"
name = "healthcare.hl7v23"
version = "0.1.12"

[[dependency]]
org = "wso2healthcare"
name = "healthcare.hl7v24"
version = "0.1.4"

[[dependency]]
org = "wso2healthcare"
name = "healthcare.hl7v25"
version = "0.1.4"
